spring.application.name=sistema-integrado-academico-web-api

spring.datasource.url=jdbc:postgresql://localhost:5432/academico
spring.datasource.username=${USUARIO}
spring.datasource.password=${SENHA}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=academico

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration